bindPort = 7000

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"

[auth]
method = "token"
token = "MergiLink.Key"

[[httpPlugins]]
name = "molian"
addr = "https://link.qwqo.cn"
path = "/api/node.php?id=1&"
ops = ["Login","NewProxy"]

